In [1]:
import pandas as pd
import os
import numpy as np
from Raw_Cleaner import timestamp_matcher, time_columns, file_to_df, cutter, \
    repeat, timestamp_correction

In [2]:
path = "http://35.12.130.8/study/2018-SERDP/02-raw-data/ALL-RAW/SERDP_SLEF_Burn_data/SERDP_SLEF_Sonic/SLEF_first_set_truss_burns/SERDP%20burn%20one/"

files = ["TOA5_2878.WGNover10Hz.dat","TOA5_2879.ts_data.dat",\
             "TOA5_4390.ts_data.dat","TOA5_4975.ts_data.dat",\
             "TOA5_4976.ts_data.dat","TOA5_10442.ts_data.dat",\
             "TOA5_11585.ts_data.dat"]

file_num = ["2878","2879","4390","4975","4390","4975","4976","10442","11585"]
### First Loading the files into the script
df_2878 = file_to_df(path, files[0])
df_2879 = file_to_df(path, files[1])

df_4390 = file_to_df(path, files[2])
df_4975 = file_to_df(path, files[3])[50672:102872]

df_4976 = file_to_df(path, files[4])
df_10442 = file_to_df(path, files[5])

df_11585 = file_to_df(path, files[6])

In [3]:
path_2 = "http://35.12.130.8/study/charney/raw_from_matt/BURN01/"
f = "BURN01,TRUSS_A,SONIC.txt"
df_truss_a = file_to_df(path_2, f, 0,0 )#[50671:52199]
#df_test = pd.read_csv(path_2+f,skiprows=0,)

In [4]:
list(df_truss_a["TIMESTAMP"])[-1]

Timestamp('2018-03-05 15:34:59.900000')

In [5]:
list(df_4975["TIMESTAMP"])[-1]

Timestamp('2018-03-05 15:34:59.900000')

In [6]:
#l = list(df_4975["TIMESTAMP"])
#t = list(df_truss_a["TIMESTAMP"])[-1]
#for i in range(len(l)):
#    if l[i] == t:
#        print(i)

In [7]:
df_same = df_truss_a == df_4975

ValueError: Can only compare identically-labeled DataFrame objects

In [ ]:
for j in list(df_same.columns)[:-14]:
    for i in df_same[j]:
        if i == False:
            print(i)

In [26]:
path_3 = "http://35.12.130.8/study/charney/raw_from_matt/BURN20/"
f_3 ="BURN20,TRUSS_A,SONIC.TXT"
df_b_20 = file_to_df(path_3, f_3, 0,0 )

In [27]:
df_b_20

,TIMESTAMP,RECORD,Ux_1,Uy_1,Uz_1,Ts_1,diag_rmy_1,Ux_2,Uy_2,Uz_2,...,Temp_C(5),Temp_C(6),Temp_C(7),Temp_C(8),Temp_C(9),Temp_C(10),Temp_C(11),Temp_C(12),Temp_C(13),Temp_C(14)
0,2019-05-20 14:16:00.000,7475012,-1.97,-2.68,-0.04,32.10,0,-2.77,-2.38,0.07,...,34.33,34.17,33.77,37.80,NaN,35.87,34.25,34.17,33.69,33.52
1,2019-05-20 14:16:00.100,7475013,-2.41,-2.41,-0.71,32.05,0,-2.84,-2.36,0.52,...,34.09,34.09,33.69,37.80,NaN,35.87,34.41,34.09,33.77,33.44
2,2019-05-20 14:16:00.200,7475014,-2.66,-1.80,-0.54,31.62,0,-2.87,-2.34,0.72,...,33.93,33.85,33.61,37.80,NaN,35.79,34.41,34.33,33.69,33.52
3,2019-05-20 14:16:00.300,7475015,-2.70,-1.71,-0.01,31.94,0,-2.59,-2.44,0.18,...,34.09,33.77,33.61,37.80,NaN,35.79,34.58,34.17,33.52,33.52
4,2019-05-20 14:16:00.400,7475016,-2.53,-1.90,0.24,31.61,0,-2.61,-2.29,-0.23,...,34.09,33.60,33.60,37.80,NaN,35.70,34.57,34.09,33.52,33.36
5,2019-05-20 14:16:00.500,7475017,-2.36,-2.00,-0.44,31.78,0,-3.00,-2.76,-0.51,...,33.93,33.52,33.61,37.72,NaN,35.79,34.49,33.93,33.44,33.28
6,2019-05-20 14:16:00.600,7475018,-2.25,-2.32,0.30,31.87,0,-2.54,-2.53,-0.25,...,33.93,33.52,33.61,37.80,NaN,35.71,34.58,33.93,33.20,33.12
7,2019-05-20 14:16:00.700,7475019,-2.80,-2.45,-0.57,31.77,0,-1.80,-2.48,-0.79,...,33.76,33.52,33.60,37.80,NaN,35.78,34.57,34.00,33.12,33.12
8,2019-05-20 14:16:00.800,7475020,-2.72,-2.69,-0.08,31.79,0,-1.77,-2.71,-0.06,...,33.77,33.61,33.61,37.97,NaN,35.79,34.66,34.09,33.12,33.04
9,2019-05-20 14:16:00.900,7475021,-2.66,-3.06,0.20,31.92,0,-2.43,-2.61,-0.14,...,33.69,33.52,33.61,37.97,NaN,35.79,34.74,33.93,33.12,32.96
10,2019-05-20 14:16:01.000,7475022,-2.54,-2.98,0.31,31.95,0,-2.08,-2.51,-0.12,...,33.69,33.52,33.61,38.13,NaN,35.87,34.74,33.93,33.04,32.96
11,2019-05-20 14:16:01.100,7475023,-2.86,-3.13,0.34,31.66,0,-2.19,-2.28,-0.22,...,33.68,33.44,33.44,38.28,NaN,35.86,34.57,33.76,33.12,33.03
12,2019-05-20 14:16:01.200,7475024,-2.85,-2.48,-0.10,31.63,0,-2.04,-2.71,-0.26,...,33.77,33.44,33.44,38.37,NaN,35.87,34.41,33.77,33.20,33.04
13,2019-05-20 14:16:01.300,7475025,-2.91,-2.35,0.14,31.67,0,-2.91,-2.93,-0.53,...,33.61,33.28,33.28,38.45,NaN,35.87,34.41,33.77,33.20,32.96
14,2019-05-20 14:16:01.400,7475026,-3.59,-2.06,0.21,31.77,0,-2.36,-3.45,0.01,...,33.60,33.12,33.12,38.61,NaN,35.86,34.25,33.76,33.12,32.95
15,2019-05-20 14:16:01.500,7475027,-3.14,-1.94,0.46,31.74,0,-2.21,-3.23,-0.21,...,33.60,33.12,33.03,38.44,NaN,35.86,34.25,33.68,33.12,32.95
16,2019-05-20 14:16:01.600,7475028,-2.08,-1.95,0.06,31.90,0,-2.57,-3.30,-0.48,...,33.60,33.12,32.95,38.44,NaN,35.78,34.25,33.60,33.20,33.12
17,2019-05-20 14:16:01.700,7475029,-2.58,-0.15,-0.14,31.82,0,-2.13,-3.31,0.11,...,33.60,33.12,32.79,38.44,NaN,35.78,34.25,33.60,33.12,32.87
18,2019-05-20 14:16:01.800,7475030,-2.43,-1.24,-0.15,31.82,0,-2.13,-2.97,-0.01,...,33.60,33.12,32.79,38.28,NaN,35.70,34.09,33.60,32.95,32.79
19,2019-05-20 14:16:01.900,7475031,-2.77,-1.65,0.44,32.02,0,-2.34,-2.77,0.54,...,33.44,32.96,32.80,38.13,NaN,35.63,34.17,33.52,32.80,32.63
20,2019-05-20 14:16:02.000,7475032,-2.89,-1.06,0.60,31.92,0,-2.30,-2.59,0.12,...,33.36,32.79,32.79,37.96,NaN,35.54,34.17,33.44,32.71,32.39
21,2019-05-20 14:16:02.100,7475033,-2.97,-1.08,0.13,32.04,0,-2.40,-2.51,0.19,...,33.20,32.79,32.79,37.96,NaN,35.54,34.09,33.44,32.63,32.39
22,2019-05-20 14:16:02.200,7475034,-2.28,-1.08,-0.32,32.02,0,-2.51,-2.71,-0.14,...,33.12,32.63,32.79,37.88,NaN,35.54,34.09,33.28,32.55,32.47
23,2019-05-20 14:16:02.300,7475035,-2.49,-1.10,-0.34,32.02,0,-2.21,-2.56,-0.13,...,33.03,32.47,32.63,37.80,NaN,35.46,34.09,33.28,32.63,32.31
24,2019-05-20 14:16:02.400,7475036,-3.00,-0.46,-0.19,32.27,0,-2.75,-2.04,-0.65,...,32.79,32.47,32.63,37.64,NaN,35.46,34.09,33.36,32.63,32.06
25,2019-05-20 14:16:02.500,7475037,-2.63,-0.82,-0.22,31.94,0,-2.41,-2.00,-0.36,...,32.87,32.55,32.63,37.48,NaN,35.38,34.09,33.52,32.47,31.98
26,2019-05-20 14:16:02.600,7475038,-2.46,-0.53,-0.05,32.18,0,-2.23,-2.52,-0.34,...,33.12,32.71,32.63,37.32,NaN,35.30,34.25,33.76,32.39,31.98
27,2019-05-20 14:16:02.700,7475039,-2.28,-0.44,0.06,32.27,0,-2.12,-2.10,0.04,...,32.95,32.63,32.63,37.48,NaN,35.30,34.09,33.60,32.31,31.98
28,2019-05-20 14:16:02.800,7475040,-2.04,-1.18,-0.02,31.92,0,-2.45,-2.17,-0.12,...,32.95,32.63,32.71,37.48,NaN,35.22,34.09,33.44,32.14,32.06
29,2019-05-20 14:16:02.900,7475041,-2.14,-1.18,0.11,31.78,0,-2.74,-2.33,-0.11,...,32.79,32.55,32.63,37.64,NaN,35.14,34.00,33.44,32.22,32.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11970,2019-05-20 14:35:57.000,7486982,-2.27,-2.01,-0.11,32.48,0,-2.27,-2.07,-0.06,...,34.04,33.64,32.75,36.54,34.28,34.44,NaN,32.75,31.86,32.02
11971,2019-05-20 14:35:57.100,7486983,-2.54,-2.15,-0.23,32.30,0,-2.16,-2.03,-0.06,...,34.12,33.47,32.66,36.62,34.28,34.44,NaN,32.66,31.85,32.01
11972,2019-05-20 14:35:57.200,7486984,-2.35,-2.34,0.09,32.59,0,-1.90,-1.93,-0.05,...,34.28,33.47,32.74,36.54,34.44,34.44,NaN,32.74,31.85,32.09
11973,2019-05-20 14:35:57.300,7486985,-2.31,-2.31,0.20,32.60,0,-1.75,-1.90,0.10,...,34.36,33.47,32.66,36.54,34.36,34.36,NaN,32.66,31.85,32.01
11974,2019-05-20 14:35:57.400,7486986,-2.44,-2.08,0.16,33.00,0,-2.17,-2.17,0.31,...,34.28,33.47,32.66,36.54,34.28,34.36,NaN,32.66,31.85,32.01
11975,2019-05-20 14:35:57.500,7486987,-2.76,-2.22,0.36,33.10,0,-2.37,-2.16,0.35,...,34.20,33.47,32.74,36.62,34.68,34.28,NaN,32.58,31.93,32.01
11976,2019-05-20 14:35:57.600,7486988,-3.45,-2.00,0.81,32.43,0,-1.91,-2.03,0.43,...,34.28,33.47,32.66,36.70,34.76,34.28,NaN,32.74,31.93,32.09
11977,2019-05-20 14:35:57.700,7486989,-2.70,-2.17,0.45,32.84,0,-1.59,-2.33,0.43,...,34.20,33.47,32.82,36.86,34.92,34.28,NaN,32.74,31.93,32.01
11978,2019-05-20 14:35:57.800,7486990,-2.46,-2.56,0.42,32.78,0,-1.45,-2.39,0.32,...,34.12,33.47,32.82,37.02,34.92,34.44,NaN,32.90,31.93,32.09
11979,2019-05-20 14:35:57.900,7486991,-2.64,-2.20,-0.16,32.84,0,-1.76,-2.20,0.34,...,34.28,33.47,32.82,37.02,35.09,34.44,NaN,33.06,31.93,32.17
11980,2019-05-20 14:35:58.000,7486992,-2.77,-2.58,-0.12,32.35,0,-1.76,-2.13,0.25,...,34.12,33.63,32.82,37.18,35.41,34.52,NaN,32.98,31.93,32.17
11981,2019-05-20 14:35:58.100,7486993,-3.23,-2.53,-0.13,31.64,0,-1.17,-2.20,0.53,...,34.12,33.63,32.90,37.35,35.49,34.76,NaN,32.98,31.93,32.17
11982,2019-05-20 14:35:58.200,7486994,-3.18,-2.30,-0.51,32.42,0,-1.33,-1.87,0.32,...,34.12,33.63,32.90,37.51,36.06,34.84,NaN,33.06,32.01,32.17
11983,2019-05-20 14:35:58.300,7486995,-2.29,-2.14,-0.12,32.25,0,-0.61,-1.83,0.44,...,34.28,33.79,32.82,37.83,36.38,35.01,NaN,33.23,32.17,32.17
11984,2019-05-20 14:35:58.400,7486996,-3.15,-2.70,0.12,31.91,0,-1.20,-2.43,0.11,...,34.28,33.95,32.90,37.91,36.06,35.25,NaN,33.39,32.26,32.34
11985,2019-05-20 14:35:58.500,7486997,-3.79,-3.31,-0.05,32.40,0,-1.12,-2.06,-0.23,...,34.44,33.95,32.82,37.99,35.81,35.17,NaN,33.39,32.26,32.34
11986,2019-05-20 14:35:58.600,7486998,-3.62,-2.80,-0.20,32.10,0,-1.23,-2.20,-0.28,...,34.44,34.12,32.98,37.91,35.73,35.33,NaN,33.31,32.17,32.34
11987,2019-05-20 14:35:58.700,7486999,-2.71,-2.82,-0.56,31.72,0,-1.47,-1.81,-0.40,...,34.68,34.12,32.90,37.91,35.73,35.25,NaN,33.31,32.26,32.34
11988,2019-05-20 14:35:58.800,7487000,-2.57,-2.14,0.00,31.58,0,-1.27,-1.87,-0.44,...,34.68,33.95,32.98,37.83,35.57,35.33,NaN,33.39,32.26,32.42
11989,2019-05-20 14:35:58.900,7487001,-2.60,-2.45,0.02,31.57,0,-1.26,-1.54,0.31,...,34.52,33.95,32.98,37.67,35.73,35.41,NaN,33.23,32.26,32.50
11990,2019-05-20 14:35:59.000,7487002,-3.03,-2.52,-0.15,31.43,0,-0.86,-1.87,-0.10,...,34.44,33.95,32.98,37.51,35.97,35.49,NaN,33.23,32.26,32.50
11991,2019-05-20 14:35:59.100,7487003,-2.76,-2.05,-0.39,31.43,0,-1.39,-1.96,0.12,...,34.36,33.87,32.98,37.35,36.22,35.49,NaN,33.23,32.26,32.50
11992,2019-05-20 14:35:59.200,7487004,-2.78,-1.94,0.01,31.51,0,-1.39,-1.97,0.08,...,34.35,33.79,32.98,37.34,36.21,35.73,NaN,33.06,32.33,32.66
11993,2019-05-20 14:35:59.300,7487005,-2.81,-3.19,0.24,32.03,0,-1.44,-2.04,0.24,...,34.28,33.79,33.06,37.35,36.06,35.73,NaN,33.15,32.42,32.50
11994,2019-05-20 14:35:59.400,7487006,-2.78,-2.77,0.16,31.48,0,-1.72,-2.15,0.12,...,34.12,33.79,32.98,37.43,36.14,35.73,NaN,33.23,32.42,32.50
11995,2019-05-20 14:35:59.500,7487007,-2.84,-2.75,-0.15,31.46,0,-1.41,-2.06,0.89,...,34.12,33.79,33.06,37.51,36.30,35.73,NaN,33.31,32.42,32.42
11996,2019-05-20 14:35:59.600,7487008,-2.99,-2.61,-0.22,31.44,0,-1.74,-1.96,0.56,...,34.12,33.87,32.98,37.67,36.06,35.73,NaN,33.63,32.58,32.42
11997,2019-05-20 14:35:59.700,7487009,-2.71,-2.69,-0.03,31.50,0,-1.65,-1.80,0.67,...,34.11,33.79,32.98,37.83,36.21,35.73,NaN,33.63,32.49,32.49
11998,2019-05-20 14:35:59.800,7487010,-2.76,-2.62,-0.28,31.50,0,-1.60,-1.47,0.72,...,34.12,33.79,32.98,37.99,36.38,35.73,NaN,33.87,32.42,32.50
11999,2019-05-20 14:35:59.900,7487011,-3.07,-2.77,0.16,32.62,0,-1.75,-2.01,0.92,...,34.11,33.79,32.82,37.99,36.37,35.73,NaN,33.79,32.49,32.49

In [28]:
path_3b="http://35.12.130.8/study/charney/burns20_to_35_fromKen/SERDP_Truss_Burns_20_to_22/"
f_3b = "TOA5_4976.ts_data.dat"
df_b_20b = pd.read_csv(path_3b+f_3b, skiprows= 4,sep= "\t",na_values='NAN')

In [29]:
headers_df = pd.read_csv(path_3b+f_3b,skiprows=1,nrows = 0,sep= "\t")
    
df_b_20b.columns=list(headers_df)

In [30]:
df_b_20b =  timestamp_correction(df_b_20b)

In [31]:
df_b_20b["TIMESTAMP"][0]

Timestamp('2019-05-20 13:24:08')

In [32]:
df_b_20["TIMESTAMP"][0]

Timestamp('2019-05-20 14:16:00')

In [43]:
start_20 = df_b_20b["TIMESTAMP"][0]
for i in range(len(df_b_20)):
    if df_b_20["TIMESTAMP"][i] ==start_20:
        print(i)
        break

In [42]:
df_b_20 == df_b_20b

ValueError: Can only compare identically-labeled DataFrame objects

In [44]:
t_s, t_e = timestamp_matcher([df_b_20,df_b_20b],["B20Matt","B20Ken"])

File: B20Matt | Start: 2019-05-20 14:16:00 | End: 2019-05-20 14:35:59.900000
File: B20Ken | Start: 2019-05-20 13:24:08 | End: 2019-05-20 18:23:24.100000

Start timestamp Pulled: 2019-05-20 14:16:00 | End Timestamp Pulled: 2019-05-20 14:35:59.900000

Timestamp that can actually be used to trim due to gaps:
Start Time: 2019-05-20 14:16:00 | End Time: 2019-05-20 14:31:00

In [46]:
df_20_Matt = cutter(df_b_20,t_s, t_e)
df_20_Ken = cutter(df_b_20b,t_s, t_e)

In [48]:
df_20_Matt == df_20_Ken

,TIMESTAMP,RECORD,Ux_1,Uy_1,Uz_1,Ts_1,diag_rmy_1,Ux_2,Uy_2,Uz_2,...,Temp_C(5),Temp_C(6),Temp_C(7),Temp_C(8),Temp_C(9),Temp_C(10),Temp_C(11),Temp_C(12),Temp_C(13),Temp_C(14)
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8971,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8972,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8973,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8974,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8975,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8976,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8977,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8978,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8979,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8980,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8981,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8982,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8983,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8984,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8985,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8986,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8987,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8988,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8989,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8990,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8991,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8992,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8993,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8994,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8995,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8996,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8997,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8998,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
8999,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
9000,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True